/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export const commandPalettePropDocs = {
  "name": "CommandPalette",
  "interfaceName": "CommandPaletteProps",
  "description": "Props for the CommandPalette component.",
  "sourcePath": "src\\components\\CommandPalette\\CommandPalette.types.ts",
  "props": [
    {
      "name": "asyncSearch",
      "type": "((query: string) => Promise<CommandItem[]>)",
      "description": "Callback to handle the search input asynchronously.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Custom classname for the command palette.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "commands",
      "type": "CommandItem[]",
      "description": "Array of available command options.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "debounceMs",
      "type": "number",
      "description": "Optional debounce time (in ms) for the search input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "emptyMessage",
      "type": "string",
      "description": "Message announced when there are no matching commands.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputAriaDescribedBy",
      "type": "string",
      "description": "Accessible description reference for the search input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputAriaLabel",
      "type": "string",
      "description": "Accessible label for the search input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputAriaLabelledBy",
      "type": "string",
      "description": "Accessible label reference for the search input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputId",
      "type": "string",
      "description": "Optional ID for the input element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputLabel",
      "type": "string",
      "description": "Optional visible or screen-reader-only label for the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "isOpen",
      "type": "boolean",
      "description": "Whether the command palette is currently open.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "listAriaLabel",
      "type": "string",
      "description": "Accessible label for the command results list.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "listboxId",
      "type": "string",
      "description": "Optional ID for the listbox element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "modal",
      "type": "boolean",
      "description": "Whether the palette should behave like a modal dialog for assistive tech.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onClose",
      "type": "() => void",
      "description": "Callback to close the command palette.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "paletteId",
      "type": "string",
      "description": "Optional ID for the palette container/dialog.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "placeholder",
      "type": "string",
      "description": "Optional placeholder for the input field.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "restoreFocusOnClose",
      "type": "boolean",
      "description": "Whether focus should return to the trigger element on close.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "resultsAnnouncement",
      "type": "string",
      "description": "Accessible live region message prefix for result count updates.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the palette ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the palette ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "The state of the command palette ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme style for the palette ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "trapFocus",
      "type": "boolean",
      "description": "Whether focus should be trapped while the palette is open.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};

