/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export const dataTablePropDocs = {
  "name": "DataTable",
  "interfaceName": "DataTableProps",
  "description": "Props for the DataTable component.",
  "sourcePath": "src\\components\\DataTable\\DataTable.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Accessible description reference for the table. Useful for tying helper or instructional text to the table.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for screen readers. Use this when there is no visible caption or heading tied to the table.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Accessible labelledby reference for the table. Prefer this when a visible heading already labels the table.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "caption",
      "type": "string",
      "description": "Optional visible or screen-reader-only caption text for the table. A table caption is the preferred built-in table label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional class name for the table wrapper.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "colCount",
      "type": "number",
      "description": "Total column count override. Helpful when rendering dynamic or grouped columns in advanced cases.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "columns",
      "type": "Column<T>[]",
      "description": "Array of column definitions.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data",
      "type": "T[]",
      "description": "Array of row data objects.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "defaultSortKey",
      "type": "keyof T",
      "description": "Default key to sort by on initial render.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "defaultSortOrder",
      "type": "\"desc\" | \"asc\"",
      "description": "Default sort order on initial render ('asc' | 'desc').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "emptyMessage",
      "type": "string",
      "description": "Text shown when no rows are available.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "getRowAriaDescription",
      "type": "((row: T, index: number) => string)",
      "description": "Optional row description for screen readers. Only used when rows are interactive.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "getRowAriaLabel",
      "type": "((row: T, index: number) => string)",
      "description": "Optional accessible label for interactive rows. Only used when onRowClick is provided.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "getSortAnnouncement",
      "type": "((column: Column<T>, sortOrder: \"asc\" | \"desc\") => string)",
      "description": "Live region text announced when sorting changes. Receives the active column and current order.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "getSortAriaLabel",
      "type": "((column: Column<T>, sortOrder: \"asc\" | \"desc\", isActive: boolean) => string)",
      "description": "Accessible label for the sort buttons/controls. Receives the column label and current sort order.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "hideCaption",
      "type": "boolean",
      "description": "Whether the caption should be visually hidden. Useful when you want semantic labeling without visible UI.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the table is currently loading data.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loadingMessage",
      "type": "string",
      "description": "Accessible and/or visible loading message.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onRowClick",
      "type": "((row: T) => void)",
      "description": "Optional callback when a row is clicked.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onSortChange",
      "type": "((key: keyof T, order: \"asc\" | \"desc\") => void)",
      "description": "Function to handle server-side sorting.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to use outline styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the table ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "rowCount",
      "type": "number",
      "description": "Total row count override. Helpful for virtualized or server-paginated tables.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rowKey",
      "type": "((row: T) => string | number)",
      "description": "Function to derive a unique key for each row.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "serverSort",
      "type": "boolean",
      "description": "Whether to enable server-side sorting.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the data table ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the table ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "striped",
      "type": "boolean",
      "description": "Whether to use striped row styling.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling the table ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling"
    }
  ]
};

