/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export const emptyStatePropDocs = {
  "name": "EmptyState",
  "interfaceName": "EmptyStateProps",
  "description": "Props for the EmptyState component.",
  "sourcePath": "src\\components\\EmptyState\\EmptyState.types.ts",
  "props": [
    {
      "name": "actionAriaLabel",
      "type": "string",
      "description": "Optional accessible label for the action button. Helpful when the visible action text is ambiguous.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "actionLabel",
      "type": "ReactNode",
      "description": "Optional label for an action button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional custom accessible description reference for the empty state region. If provided, overrides the generated message association.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Optional custom accessible label for the entire empty state region. Useful when the title is visual but not sufficient as a landmark label.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional custom accessible label reference for the entire empty state region. If provided, overrides the generated title association.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "icon",
      "type": "IconType",
      "description": "Optional icon component (e.g., from react-icons).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconAriaLabel",
      "type": "string",
      "description": "Accessible label for the icon when it is not decorative.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconDecorative",
      "type": "boolean",
      "description": "Whether the icon should be announced to assistive technology. Defaults to false.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional ID for the root empty state container. Useful for external aria-labelledby / aria-describedby wiring.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "message",
      "type": "ReactNode",
      "description": "Optional supporting message below the title.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onActionClick",
      "type": "(() => void)",
      "description": "Optional click handler for the action button.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether the component uses outline styles.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "role",
      "type": "AriaRole",
      "description": "Optional role override. Defaults to \"region\" when a title exists, otherwise no role is applied.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Controls the rounding of the component ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Controls the shadow of the component ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size modifier ('xs' | 'small' | 'medium' | 'large' | 'xl').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "The EmptyState state ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theming option for styling ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "description": "Title text displayed prominently.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};

