/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export const notificationCenterPropDocs = {
  "name": "NotificationCenter",
  "interfaceName": "NotificationCenterProps",
  "description": "Props for the NotificationCenter component.",
  "sourcePath": "src\\components\\NotificationCenter\\NotificationCenter.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional ID of an element that describes the notification center.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the notification center region.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional ID of an external element that labels the notification center.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "clearAllAriaLabel",
      "type": "string",
      "description": "Accessible label for the clear all button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "clearOldOnOverflow",
      "type": "boolean",
      "description": "If true, clears the oldest notifications when over the maximum.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "controlRounding",
      "type": "RoundingType",
      "description": "Rounding for the notification control. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "controlShadow",
      "type": "ShadowType",
      "description": "Shadow for the notification control. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "dismissButtonLabelPrefix",
      "type": "string",
      "description": "Prefix used to build dismiss button labels.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "emptyMessage",
      "type": "string",
      "description": "Accessible text announced when there are no notifications.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fetchNotifications",
      "type": "(() => Promise<Notification[]>)",
      "description": "Optional callback function to fetch more notifications.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "list-aria-label",
      "type": "string",
      "description": "Accessible label for the notifications list when needed.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "liveRegionAtomic",
      "type": "boolean",
      "description": "Whether the live region should announce the entire region or only changed content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "liveRegionPoliteness",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Live region politeness level for notification updates.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "liveRegionRelevant",
      "type": "\"text\" | \"additions\" | \"additions removals\" | \"additions text\" | \"all\" | \"removals\" | \"removals additions\" | \"removals text\" | \"text additions\" | \"text removals\"",
      "description": "Which kinds of changes should be announced by assistive technology.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "maxNotifications",
      "type": "number",
      "description": "Maximum number of notifications to display.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "notificationRounding",
      "type": "RoundingType",
      "description": "Rounding of the notification. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "notifications",
      "type": "Notification[]",
      "description": "Array of notifications to display.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "notificationShadow",
      "type": "ShadowType",
      "description": "Shadow of the notification. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onClearAll",
      "type": "(() => void)",
      "description": "Optional callback function to clear all notifications.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onRemove",
      "type": "(id: string) => void",
      "description": "Callback function to remove a notification by its ID.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "pollInterval",
      "type": "number",
      "description": "Optional interval (in milliseconds) at which to fetch more notifications.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "setNotifications",
      "type": "React.Dispatch<React.SetStateAction<Notification[]>>",
      "description": "Callback function to set the notifications array.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "showClearAll",
      "type": "boolean",
      "description": "Whether to show a \"Clear All\" button if notifications are present.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};

