/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export const scrollToTopPropDocs = {
  "name": "ScrollToTop",
  "interfaceName": "ScrollToTopProps",
  "description": "Props for the ScrollToTopBase component.",
  "sourcePath": "src\\components\\ScrollToTop\\ScrollToTop.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional accessible description id applied to the button.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the scroll-to-top button.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional id of an external label element applied to the button. When provided, this takes precedence over \"aria-label\" for accessible naming.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional custom class names for the root element of the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test identifier for the component, used to target it in testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional id for the root element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "offset",
      "type": "number",
      "description": "The scroll offset (in pixels) from the top of the page at which the button becomes visible.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "React.AriaRole",
      "description": "Optional role for the outer wrapper if semantic grouping is needed.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Optional rounding style applied to the button.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Optional shadow style for the button.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "title",
      "type": "string",
      "description": "Optional title attribute for the button. Defaults to the same value as \"aria-label\" when not provided.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "wrapperAriaLabel",
      "type": "string",
      "description": "Optional accessible label for the wrapper when a semantic role is used.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};

