/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export const sidebarPropDocs = {
  "name": "Sidebar",
  "interfaceName": "SidebarProps",
  "description": "",
  "sourcePath": "src\\components\\Sidebar\\Sidebar.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ID reference to one or more elements that describe the sidebar navigation landmark.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the navigation landmark. Prefer the kebab-case ARIA prop for consistency with other React ARIA props.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ID reference to one or more elements that label the sidebar navigation landmark. Takes precedence over aria-label when both are provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name(s) for applying custom styles.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks like Jest and React Testing Library.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "footerAriaLabel",
      "type": "string",
      "description": "Optional label for the footer landmark when footer content is rendered. Example: \"Sidebar footer links\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerAriaLabelledBy",
      "type": "string",
      "description": "Optional ID reference to label the footer landmark.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerLinks",
      "type": "SidebarFooterLink[]",
      "description": "Array of footer links to render when `showFooter` is `true`.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerVersion",
      "type": "string",
      "description": "Optional version string displayed in the sidebar footer. Example: \"v1.2.3\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "getExpandButtonAriaDescription",
      "type": "((link: SidebarLink, isOpen: boolean) => string)",
      "description": "Optional accessible description generator for expandable parent items.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "getExpandButtonAriaLabel",
      "type": "((link: SidebarLink, isOpen: boolean) => string)",
      "description": "Optional accessible label generator for expandable parent items. Useful when you want screen readers to hear something more descriptive than the visible text alone.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "hasActiveChild",
      "type": "((link: SidebarLink) => boolean)",
      "description": "Optional callback used to determine whether a link contains an active child.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "isLinkActive",
      "type": "((link: SidebarLink) => boolean)",
      "description": "Optional callback used to determine whether a link should be styled as active.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "links",
      "type": "SidebarLink[]",
      "description": "Array of navigation links to render in the sidebar. Each link may optionally include a nested submenu.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "If true, the sidebar is styled with an outline variant. Defaults to `false`.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the sidebar container. - \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the sidebar container. - \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "showFooter",
      "type": "boolean",
      "description": "Whether to display a footer section at the bottom of the sidebar. Defaults to `false`.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State variant for styling. Typically used to apply semantic states to the component. - \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme for styling. Determines the base color scheme for the sidebar. - \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    }
  ]
};

