/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export const spinnerPropDocs = {
  "name": "Spinner",
  "interfaceName": "SpinnerProps",
  "description": "Props for the Spinner component.",
  "sourcePath": "src\\components\\Spinner\\Spinner.types.ts",
  "props": [
    {
      "name": "aria-busy",
      "type": "boolean",
      "description": "Whether the related region is busy. Defaults to true.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ID of element(s) that describe the spinner.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label announced by screen readers. Falls back to `label`, then \"Loading\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ID of element(s) that label the spinner. Takes precedence over `aria-label` when provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "ARIA live region politeness. Defaults to \"polite\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class names for styling customization.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test ID for testing frameworks (e.g., for use with Jest or Cypress).",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Optional visible label for the spinner.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "React.AriaRole",
      "description": "Optional ARIA role. Defaults to \"status\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the spinner. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "number",
      "description": "The size of the spinner (in pixels).",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "The state of the spinner. One of: \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "The theme color of the spinner. One of: \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    }
  ]
};

