/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export const stepperPropDocs = {
  "name": "Stepper",
  "interfaceName": "StepperProps",
  "description": "Props for the Stepper component.",
  "sourcePath": "src\\components\\Stepper\\Stepper.types.ts",
  "props": [
    {
      "name": "activeStep",
      "type": "number",
      "description": "The index of the currently active step.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ID of an element that describes the stepper container.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the stepper container. Use this when there is no visible external label.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ID of an element that labels the stepper container. Takes precedence over aria-label when provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class names for styling customization.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing purposes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disableBackNavigation",
      "type": "boolean",
      "description": "If true, disables backward navigation (users cannot go to previous steps).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "getStepAriaLabel",
      "type": "((step: Step, index: number, stepCount: number, isActive: boolean, isCompleted: boolean) => string)",
      "description": "Optional custom accessible label generator for each step button.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "groupLabel",
      "type": "string",
      "description": "Fallback hidden label text when no aria-label or aria-labelledby is provided. Defaults to \"Progress Stepper\".",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onStepClick",
      "type": "((stepIndex: number) => void)",
      "description": "Optional callback when a step is clicked.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "orientation",
      "type": "OrientationType",
      "description": "Orientation of the stepper. \"horizontal\" | \"vertical\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the stepper buttons. \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the stepper buttons. \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the stepper icons. \"xs\" | \"small\" | \"medium\" | \"large\" | \"xl\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the stepper. \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "steps",
      "type": "Step[]",
      "description": "An array of steps, each with a label and optional icon.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme style for the stepper. \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    }
  ]
};

