/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export const timelinePropDocs = {
  "name": "Timeline",
  "interfaceName": "TimelineProps",
  "description": "Props for the Timeline component.",
  "sourcePath": "src\\components\\Timeline\\Timeline.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional aria-describedby for the timeline root.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the timeline. Defaults to \"Timeline\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional aria-labelledby for the timeline root. When provided, this should take precedence over \"aria-label\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing purposes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "items",
      "type": "TimelineItem[]",
      "description": "Array of timeline items to display.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "orientation",
      "type": "OrientationType",
      "description": "Orientation of the timeline. \"vertical\" | \"horizontal\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "React.AriaRole",
      "description": "Optional role override for the root element. Defaults to \"list\" when not provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the component. \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style of the component. \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme to apply for styling. \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    }
  ]
};

