/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export const togglePropDocs = {
  "name": "Toggle",
  "interfaceName": "ToggleProps",
  "description": "Props for the Toggle component.",
  "sourcePath": "src\\components\\Toggle\\Toggle.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "References the id of an element that describes the toggle, such as hint text or supporting content.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-disabled",
      "type": "boolean",
      "description": "Explicitly communicates disabled state to assistive technologies. Normally inferred from `disabled`, but exposed for flexibility.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-errormessage",
      "type": "string",
      "description": "References the id of an element containing an error message.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "description": "Indicates whether the current value is invalid.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for screen readers. Best used when no visible label is rendered.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "References the id of an element that labels the toggle. Takes precedence over aria-label when provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "checked",
      "type": "boolean",
      "description": "Indicates whether the toggle is in the \"on\" (`true`) or \"off\" (`false`) state.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "If true, disables user interaction with the toggle.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional id for the toggle button. If not provided, one will be generated automatically.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Optional label to be displayed next to the toggle switch.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "(checked: boolean) => void",
      "description": "Callback that is invoked when the toggle's state changes. Receives the new boolean state as an argument.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding applied to the toggle. \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style applied to the toggle. \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size variant for the toggle. \"xs\" | \"small\" | \"medium\" | \"large\" | \"xl\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the toggle. \"\" | \"success\" | \"error\" | \"warning\" | \"disabled\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "tabIndex",
      "type": "number",
      "description": "Optional tab index for focus management.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling the toggle. \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    }
  ]
};

