/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export const typographyPropDocs = {
  "name": "Typography",
  "interfaceName": "TypographyProps",
  "description": "",
  "sourcePath": "src\\components\\Typography\\Typography.types.ts",
  "props": [
    {
      "name": "align",
      "type": "TypographyAlign",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-atomic",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-busy",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-hidden",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "as",
      "type": "ElementType",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "id",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "italic",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "noWrap",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "AriaRole",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "srOnly",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "style",
      "type": "CSSProperties",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "TypographyTheme",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "title",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "truncate",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "underline",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "TypographyVariant",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "weight",
      "type": "TypographyWeight",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};

