/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const accordionPropDocs: GeneratedComponentDoc = {
  "name": "Accordion",
  "interfaceName": "AccordionProps",
  "description": "Props for the Accordion component.",
  "sourcePath": "src\\components\\Accordion\\Accordion.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ID reference for describing the accordion toggle button. This can supplement or replace the generated description ID.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the accordion toggle button. Useful when the visible title is not descriptive enough.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ID reference for labeling the accordion toggle button. Prefer this when an external visible label already exists.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "asyncContent",
      "type": "boolean",
      "description": "If true, the accordion content is loaded asynchronously.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "The content to display when the accordion is expanded.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional custom class names for the wrapper element.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "customCollapsedIcon",
      "type": "ReactNode",
      "description": "Custom icon to display when the accordion is collapsed.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "customExpandedIcon",
      "type": "ReactNode",
      "description": "Custom icon to display when the accordion is expanded.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "description",
      "type": "string",
      "description": "Accessible description. This can be announced to assistive technologies via aria-describedby.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "If true, disables user interaction and styles the accordion as disabled.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "expanded",
      "type": "boolean",
      "description": "If set, enables controlled mode. Determines whether the accordion is expanded.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconPosition",
      "type": "\"left\" | \"right\"",
      "description": "Position of accordion toggle icon.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional custom ID for the accordion content section. If not provided, a unique ID will be generated.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "initiallyExpanded",
      "type": "boolean",
      "description": "If true, the accordion is initially expanded (uncontrolled mode).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "isToggleable",
      "type": "boolean",
      "description": "If true, the accordion can be toggled open or closed. If false, the accordion is always expanded.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "lazyLoad",
      "type": "boolean",
      "description": "If true, the accordion content will be loaded lazily.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loadingAriaLabel",
      "type": "string",
      "description": "Announces loading state for assistive technologies when async content is enabled.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onToggle",
      "type": "((expanded: boolean) => void)",
      "description": "Callback triggered when the accordion header is toggled. Receives the new expanded state.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "If true, applies an outline style to the accordion.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "regionAriaDescribedBy",
      "type": "string",
      "description": "ID reference for describing the content region.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "regionAriaLabel",
      "type": "string",
      "description": "Accessible label for the expanded content region. Usually not needed if ariaLabelledBy/aria-labelledby is already sufficient.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "regionAriaLabelledBy",
      "type": "string",
      "description": "ID reference for labeling the content region. Overrides the default button-based relationship when needed.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "React.AriaRole",
      "description": "Optional role override for the outer wrapper. Leave undefined in most cases.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Controls the rounding of the accordion.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Controls the shadow of the accordion.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "The size of the accordion.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "The state of the accordion ('success' | 'error' | 'warning').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "The theme color of the accordion.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "title",
      "type": "string",
      "description": "The title text displayed in the accordion header.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
