/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const breadcrumbsPropDocs: GeneratedComponentDoc = {
  "name": "Breadcrumbs",
  "interfaceName": "BreadcrumbsProps",
  "description": "Props for the Breadcrumbs component.",
  "sourcePath": "src\\components\\Breadcrumbs\\Breadcrumbs.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional ID of another element that describes this breadcrumb navigation.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the breadcrumb navigation. Defaults to \"Breadcrumbs\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional ID of another element that labels this breadcrumb navigation. Prefer this when a visible heading already exists.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Disables interaction and styles as disabled.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "items",
      "type": "Breadcrumb[]",
      "description": "An array of breadcrumb items.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "maxVisible",
      "type": "number",
      "description": "Maximum number of visible items before collapsing into an ellipsis.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to use the outline style.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style to apply to the breadcrumbs ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "separator",
      "type": "ReactNode",
      "description": "Optional custom separator node between breadcrumb items. Defaults to a right chevron icon.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style to apply to the breadcrumbs ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the breadcrumbs ('xs' | 'small' | 'medium' | 'large' | 'xl').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the breadcrumbs ('success' | 'error' | 'warning' | 'disabled' | ''). Used for visual feedback.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme style to apply to the breadcrumbs ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling"
    }
  ]
};
