/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const buttonPropDocs: GeneratedComponentDoc = {
  "name": "Button",
  "interfaceName": "ButtonProps",
  "description": "Props for the reusable Button component.",
  "sourcePath": "src\\components\\Button\\Button.types.ts",
  "props": [
    {
      "name": "_target",
      "type": "React.HTMLAttributeAnchorTarget",
      "description": "Optional target for link rendering. Example: \"_blank\", \"_self\", \"_parent\", \"_top\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-atomic",
      "type": "boolean",
      "description": "Whether assistive technologies should treat live updates as atomic.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-busy",
      "type": "boolean",
      "description": "Indicates whether the element is busy. Usually derived automatically from `loading`.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-controls",
      "type": "string",
      "description": "Identifies the element controlled by this button, such as a menu, dialog, accordion panel, or disclosure region.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-current",
      "type": "boolean | \"page\" | \"step\" | \"location\" | \"date\" | \"time\"",
      "description": "Indicates that this button represents the current item within a set. Most useful when rendering as a link-like control.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "References the element(s) that describe this button. Useful for extra instructions or status messaging.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-disabled",
      "type": "boolean",
      "description": "Indicates whether the control is perceivable as disabled to assistive tech. Usually derived automatically when rendered as a disabled link.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-expanded",
      "type": "boolean",
      "description": "Indicates whether the controlled element is expanded or collapsed. Commonly used for disclosure buttons.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-haspopup",
      "type": "boolean | \"dialog\" | \"grid\" | \"listbox\" | \"menu\" | \"tree\"",
      "description": "Indicates that activating the button opens a popup such as a menu, dialog, listbox, tree, or grid.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for screen readers. Required for icon-only buttons.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "References the element(s) that label this button. Useful when the visible label lives outside the button.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Optional live-region politeness for loading or dynamic content updates.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-pressed",
      "type": "boolean | \"mixed\"",
      "description": "Indicates the pressed state for toggle buttons.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "as",
      "type": "React.ElementType<any, keyof React.JSX.IntrinsicElements>",
      "description": "Optional element or component override. Example: \"a\", \"button\", Link",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Child content to display inside the button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name(s) for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the button should be disabled.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "description": "Whether the button should take up the full width of its container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "href",
      "type": "string",
      "description": "If provided, button will render as a link pointing to this href.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "icon",
      "type": "ComponentType<{ className?: string; \"aria-hidden\"?: boolean; focusable?: boolean; }>",
      "description": "Optional icon component to render inside the button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "isExternal",
      "type": "boolean",
      "description": "If true, opens the link in a new tab (used with `href`).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether to show a loading indicator instead of the children.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loadingLabel",
      "type": "string",
      "description": "Optional accessible text announced while loading. Defaults to \"Loading\" in the component if not provided.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onClick",
      "type": "((e: React.MouseEvent<HTMLElement>) => void)",
      "description": "Click event handler for the button.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to use outline styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the button ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the button ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the button ('xs' | 'small' | 'medium' | 'large' | 'xl').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the button ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme style of the button ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "type",
      "type": "\"button\" | \"reset\" | \"submit\"",
      "description": "Button type for native `<button>` elements ('button' | 'reset' | 'submit').",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
