/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const cardPropDocs: GeneratedComponentDoc = {
  "name": "Card",
  "interfaceName": "CardProps",
  "description": "Props for the customizable Card component.",
  "sourcePath": "src\\components\\Card\\Card.types.ts",
  "props": [
    {
      "name": "actionButtonClassName",
      "type": "string",
      "description": "Custom class name for each action button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "actionButtons",
      "type": "ActionButton[]",
      "description": "List of action buttons to render in the footer.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "actionsClassName",
      "type": "string",
      "description": "Custom class name for the actions wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "align",
      "type": "\"left\" | \"right\" | \"center\"",
      "description": "Alignment of card content ('left' | 'right' | 'center').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-atomic",
      "type": "boolean",
      "description": "Marks the card as atomic for live region updates.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-controls",
      "type": "string",
      "description": "Indicates the controlled element id if the card acts as a controller.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-current",
      "type": "boolean | \"page\" | \"step\" | \"location\" | \"date\" | \"time\"",
      "description": "Indicates current item state when the card is used in navigation-like UIs.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional ARIA description reference ID.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-expanded",
      "type": "boolean",
      "description": "Indicates expanded state if the card controls collapsible content.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Optional ARIA label for the card.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional ARIA label reference ID for accessibility.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Live-region politeness, usually only useful for dynamic card content.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "bodyClassName",
      "type": "string",
      "description": "Custom class name for the body section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "border",
      "type": "BorderType",
      "description": "Optional border width for the card ('none' | 'xs' | 'small' | 'medium' | 'large' | 'xl').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "cardIcon",
      "type": "IconType",
      "description": "Optional icon to display beside the title.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Optional custom children passed into the body.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "childrenClassName",
      "type": "string",
      "description": "Custom class name for the children wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Custom class name for the card container.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Custom class name for the content wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for test targeting.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "description",
      "type": "string",
      "description": "Optional description displayed in the body.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "descriptionClassName",
      "type": "string",
      "description": "Custom class name for the description text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "descriptionId",
      "type": "string",
      "description": "Optional override for the generated description id.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Indicates disabled state for the card.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerClassName",
      "type": "string",
      "description": "Custom class name for the footer section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "headerClassName",
      "type": "string",
      "description": "Custom class name for the header section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "headerId",
      "type": "string",
      "description": "Optional override for the generated header id.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconClassName",
      "type": "string",
      "description": "Custom class name for the icon wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional id for the card root.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "imageAlt",
      "type": "string",
      "description": "Image alt text. Use empty string for decorative images.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "imageClassName",
      "type": "string",
      "description": "Custom class name for the image element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "imageDecorative",
      "type": "boolean",
      "description": "Marks the image as decorative and forces empty alt text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "imageFill",
      "type": "boolean",
      "description": "Use fill layout for the image (next/image: fill; core: ratio-box render)",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "imageHeight",
      "type": "number",
      "description": "Explicit height for the image (forwarded to next/image or <img>)",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "imageUrl",
      "type": "CardImageSource",
      "description": "Image URL or static asset used as the card's visual. Can be a string or an object with { src, width, height }.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "imageWidth",
      "type": "number",
      "description": "Explicit width for the image (forwarded to next/image or <img>)",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "layout",
      "type": "OrientationType",
      "description": "Layout orientation of the card ('horizontal' | 'vertical').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the card is in a loading state (shows skeleton).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "mediaClassName",
      "type": "string",
      "description": "Custom class name for the media/image wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Outlines card instead of solid fill.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "renderContent",
      "type": "(() => ReactNode)",
      "description": "Custom render function for the body/content section.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "renderFooter",
      "type": "(() => ReactNode)",
      "description": "Custom render function for the footer section.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "renderHeader",
      "type": "(() => ReactNode)",
      "description": "Custom render function for the header section.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "role",
      "type": "AriaRole",
      "description": "Optional role override. Defaults to region when labeled.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Optional rounding style for the card ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "selectable",
      "type": "boolean",
      "description": "Marks the card as selectable.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "selected",
      "type": "boolean",
      "description": "Indicates selected state for selectable cards.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Optional shadow style for the card ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Card size ('xs' | 'small' | 'medium' | 'large' | 'xl').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the card ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "tabIndex",
      "type": "number",
      "description": "Optional tabindex for keyboard navigation scenarios.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme style to apply to the card ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "title",
      "type": "string",
      "description": "Optional card title displayed in the header.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "titleClassName",
      "type": "string",
      "description": "Custom class name for the title element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "useIconButtons",
      "type": "boolean",
      "description": "Whether to render action buttons as icon buttons.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
