/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const checkBoxPropDocs: GeneratedComponentDoc = {
  "name": "CheckBox",
  "interfaceName": "CheckBoxProps",
  "description": "Props for the Checkbox component.",
  "sourcePath": "src\\components\\Checkbox\\Checkbox.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ID reference(s) to element(s) that describe the checkbox. This may include helper text, error text, or external descriptions.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-errormessage",
      "type": "string",
      "description": "ID reference to the element containing the error message. Typically used together with aria-invalid.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the checkbox when no visible label is present or when a more descriptive label is needed.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ID reference(s) to element(s) that label the checkbox. If provided, this takes precedence over the internal label association.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "checked",
      "type": "boolean",
      "description": "Checked state of the checkbox.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Custom class name for additional styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "description",
      "type": "ReactNode",
      "description": "Visible helper text rendered below or beside the checkbox. Should provide extra guidance for the user.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the checkbox is disabled.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "errorMessage",
      "type": "ReactNode",
      "description": "Visible error message rendered for invalid state. This can also be referenced by assistive technologies.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "indeterminate",
      "type": "boolean",
      "description": "Whether the checkbox is in an indeterminate (mixed) state.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "invalid",
      "type": "boolean",
      "description": "Marks the checkbox as invalid. Useful when validation fails.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Label text displayed beside the checkbox.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "\"left\" | \"right\"",
      "description": "Position of the label relative to the checkbox ('left' | 'right').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "(checked: boolean) => void",
      "description": "Callback when the checkbox value changes.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether the checkbox is required.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "\"checkbox\"",
      "description": "Optional role override, though checkbox is the default semantic role.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Controls the rounding of the checkbox ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Controls the shadow of the checkbox ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the checkbox ('xs' | 'small' | 'medium' | 'large' | 'xl').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the checkbox ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Optional theme to style the checkbox ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling"
    }
  ]
};
