/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const chipGroupPropDocs: GeneratedComponentDoc = {
  "name": "ChipGroup",
  "interfaceName": "ChipGroupProps",
  "description": "",
  "sourcePath": "src\\components\\Chip\\ChipGroup\\ChipGroup.types.ts",
  "props": [
    {
      "name": "children",
      "type": "undefined",
      "description": "Children are not allowed when using `chips`.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "chips",
      "type": "ChipProps[]",
      "description": "Chips array is not allowed when using children.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional class name for the chip group container.",
      "required": false,
      "inherited": true,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": true,
      "category": "testing"
    },
    {
      "name": "onRemove",
      "type": "((id: string) => void)",
      "description": "Optional callback when a chip is removed.",
      "required": false,
      "inherited": true,
      "category": "events"
    },
    {
      "name": "position",
      "type": "PositionType",
      "description": "Default position for chips in the group.",
      "required": false,
      "inherited": true,
      "category": "props"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Default size for chips if not individually specified.",
      "required": false,
      "inherited": true,
      "category": "styling"
    }
  ]
};
