/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const chipPropDocs: GeneratedComponentDoc = {
  "name": "Chip",
  "interfaceName": "ChipProps",
  "description": "Props for the Chip component.",
  "sourcePath": "src\\components\\Chip\\Chip.types.ts",
  "props": [
    {
      "name": "autoClose",
      "type": "boolean",
      "description": "Whether the chip should close automatically after a delay.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "closeButtonAriaLabel",
      "type": "string",
      "description": "Custom accessible label for the close button. Defaults to \"Close notification\".",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "duration",
      "type": "number",
      "description": "Time in milliseconds before auto-closing (default: 3000).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "icon",
      "type": "ElementType",
      "description": "Optional icon component to show on the left side.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconAriaLabel",
      "type": "string",
      "description": "Accessible label for the leading icon when it is not decorative.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconDecorative",
      "type": "boolean",
      "description": "Whether the leading icon is decorative. When true, it will be hidden from assistive technology. Defaults to true.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional unique ID for the chip.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "message",
      "type": "string",
      "description": "Message text to display inside the chip.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "messageId",
      "type": "string",
      "description": "Optional ID for the message element. If omitted, a stable fallback based on testId/id is used.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onClose",
      "type": "(() => void)",
      "description": "Callback when the chip is closed manually or automatically.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "position",
      "type": "PositionType",
      "description": "Position of the chip on the screen ('topLeft' | 'topCenter' | 'topRight' | 'bottomLeft' | 'bottomCenter' | 'bottomRight').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "\"none\" | \"alert\" | \"log\" | \"presentation\" | \"status\"",
      "description": "ARIA role for the chip container. Defaults to \"alert\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the chip ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the chip ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the chip ('xs' | 'small' | 'medium' | 'large' | 'xl').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "stackIndex",
      "type": "number",
      "description": "Index for stacking multiple chips, useful for z-index logic.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the chip ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme color for the chip ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "usePortal",
      "type": "boolean",
      "description": "Whether to use a portal for rendering the chip.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "visible",
      "type": "boolean",
      "description": "Whether the chip is currently visible.",
      "required": true,
      "inherited": false,
      "category": "props"
    }
  ]
};
