/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const dividerPropDocs: GeneratedComponentDoc = {
  "name": "Divider",
  "interfaceName": "DividerProps",
  "description": "Props for the Divider component.",
  "sourcePath": "src\\components\\Divider\\Divider.types.ts",
  "props": [
    {
      "name": "as",
      "type": "\"div\" | \"hr\" | \"span\"",
      "description": "HTML tag to render ('div' | 'hr' | 'span').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "dashed",
      "type": "boolean",
      "description": "Whether the divider should be dashed instead of solid.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "decorative",
      "type": "boolean",
      "description": "Whether the divider is purely decorative. When true, it is hidden from assistive technology. Default: true",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Accessible label for a meaningful separator. Only used when decorative is false.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelledBy",
      "type": "string",
      "description": "ID of an element that labels this separator. Only used when decorative is false.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "length",
      "type": "string",
      "description": "Length of the divider (e.g., \"100%\", \"60px\").",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "orientation",
      "type": "OrientationType",
      "description": "Orientation of the divider ('horizontal' | 'vertical'). Default is 'horizontal'.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the divider ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme style to apply to the divider ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "thickness",
      "type": "string",
      "description": "Thickness of the divider (e.g., \"1px\", \"4px\").",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
