/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const dropdownPropDocs: GeneratedComponentDoc = {
  "name": "Dropdown",
  "interfaceName": "DropdownProps",
  "description": "Props for the Dropdown component.",
  "sourcePath": "src\\components\\Dropdown\\Dropdown.types.ts",
  "props": [
    {
      "name": "align",
      "type": "\"left\" | \"right\"",
      "description": "Menu alignment relative to the trigger ('left' | 'right').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Accessible description id(s) for the trigger button.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the trigger button. Prefer this when the trigger is icon-only.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Accessible labelledby target for the trigger button.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Custom class name for the dropdown wrapper.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "closeOnSelect",
      "type": "boolean",
      "description": "Whether the menu should close after selecting an item. Default is usually true for action menus.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "focusFirstItemOnOpen",
      "type": "boolean",
      "description": "Whether keyboard focus should move to the first item when the menu opens. Default behavior in your base already does this logically.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "items",
      "type": "DropdownItem[]",
      "description": "Array of items to render in the dropdown menu.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "menuAriaDescribedby",
      "type": "string",
      "description": "Accessible description id(s) for the menu.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "menuAriaLabel",
      "type": "string",
      "description": "Accessible label for the menu itself. Falls back to `aria-label` in many implementations.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "menuAriaLabelledby",
      "type": "string",
      "description": "Accessible labelledby target for the menu. Prefer this over `menuAriaLabel` when visible text labels the menu.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "menuClassName",
      "type": "string",
      "description": "Custom class name for the dropdown menu.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "menuId",
      "type": "string",
      "description": "Optional id for the menu element. Useful when composing with external controls/tests.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "menuProps",
      "type": "Omit<React.HTMLProps<HTMLDivElement>, \"role\" | \"id\" | \"children\">",
      "description": "Extra props applied to the menu container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "menuRounding",
      "type": "RoundingType",
      "description": "Rounding of the dropdown menu ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "menuShadow",
      "type": "ShadowType",
      "description": "Shadow style for the dropdown menu ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the dropdown ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme for styling ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "title",
      "type": "string",
      "description": "Optional title/tooltip text for the trigger.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "toggleOutline",
      "type": "boolean",
      "description": "Whether to use the outline style on the toggle button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "toggleRounding",
      "type": "RoundingType",
      "description": "Rounding of the toggle button ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "toggleShadow",
      "type": "ShadowType",
      "description": "Shadow style for the toggle button ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "triggerIcon",
      "type": "ComponentType<{ className?: string; \"aria-hidden\"?: boolean; focusable?: boolean; }>",
      "description": "Icon component used for the trigger button.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "triggerId",
      "type": "string",
      "description": "Optional id for the trigger element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "triggerProps",
      "type": "Omit<IconButtonProps, \"aria-label\" | \"aria-labelledby\" | \"aria-describedby\" | \"aria-controls\" | \"aria-expanded\" | \"aria-haspopup\" | \"onClick\" | \"icon\" | ... 4 more ... | \"outline\">",
      "description": "Extra props applied to the trigger IconButton. Keeps accessibility flexible without bloating the main API.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
