/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const fileUploadPropDocs: GeneratedComponentDoc = {
  "name": "FileUpload",
  "interfaceName": "FileUploadProps",
  "description": "Props for the FileUpload component.",
  "sourcePath": "src\\components\\FileUpload\\FileUpload.types.ts",
  "props": [
    {
      "name": "allowedFileTypes",
      "type": "string[]",
      "description": "Allowed file MIME types or file extensions (e.g. \".pdf\", \"image/png\").",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "controlRounding",
      "type": "RoundingType",
      "description": "Rounding of the control button ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "controlShadow",
      "type": "ShadowType",
      "description": "Shadow of the control button ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "description",
      "type": "string",
      "description": "Optional description text under the label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether to disable the file input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "dropzoneDescription",
      "type": "string",
      "description": "Optional custom instructions for drag-and-drop users and assistive tech.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "dropzoneRole",
      "type": "\"button\" | \"group\" | \"region\"",
      "description": "Whether the dropzone should expose a button-like role.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "enableDragAndDrop",
      "type": "boolean",
      "description": "Whether drag and drop is enabled.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "error",
      "type": "string",
      "description": "Optional error message.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "failureMessage",
      "type": "string",
      "description": "Status message announced when upload fails.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fileListAriaLabel",
      "type": "string",
      "description": "Accessible label for the selected files list.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fileRemovedMessage",
      "type": "((fileName: string, index: number) => string)",
      "description": "Message announced when a file is removed.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "filesSelectedMessage",
      "type": "((files: File[]) => string)",
      "description": "Message announced when files are selected.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional custom id for the root/input relationship.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputAriaLabel",
      "type": "string",
      "description": "Accessible label for the hidden native file input when no visible label is used.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Label displayed above the file input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "liveRegionPoliteness",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Live region politeness for status updates.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "maxFileSizeBytes",
      "type": "number",
      "description": "Maximum file size in bytes (e.g., 5MB = 5 * 1024 * 1024).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "multiple",
      "type": "boolean",
      "description": "Allows multiple file selection if true.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onFilesChange",
      "type": "((files: File[]) => void)",
      "description": "Called whenever selected files change.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onSubmit",
      "type": "(files: File[]) => void | Promise<void>",
      "description": "Called after upload completes.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to display the control button as an outline.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "outlineRounding",
      "type": "RoundingType",
      "description": "Rounding of the wrapping element ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "outlineShadow",
      "type": "ShadowType",
      "description": "Shadow of the wrapping element ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rejectedFilesAriaLabel",
      "type": "string",
      "description": "Accessible label for the rejected files list.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rejectedFilesMessage",
      "type": "((files: { name: string; reason: string; }[]) => string)",
      "description": "Message announced when rejected files are detected.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "removeFileAriaLabel",
      "type": "((fileName: string, index: number) => string)",
      "description": "Accessible label template for remove buttons.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether the file input is required.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "selectButtonAriaLabel",
      "type": "string",
      "description": "Accessible label for the upload trigger button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "The state of the file upload ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "successMessage",
      "type": "string",
      "description": "Status message announced when upload succeeds.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme for the buttons and progress bar ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "uploadButtonAriaLabel",
      "type": "string",
      "description": "Accessible label for the submit/upload button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "uploadProgress",
      "type": "number",
      "description": "External upload progress value (overrides internal simulation).",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
