/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const footerPropDocs: GeneratedComponentDoc = {
  "name": "Footer",
  "interfaceName": "FooterProps",
  "description": "Props for the Footer component.",
  "sourcePath": "src\\components\\Footer\\Footer.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Describes the footer landmark via external element IDs.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the overall footer landmark. Use when multiple contentinfo landmarks may appear on the page.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Accessible label reference for the overall footer landmark.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "attachment",
      "type": "AttachmentType",
      "description": "Attachment type for how the footer is positioned. ('static' | 'fixed' | 'sticky')",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional class name for custom styles.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "copyright",
      "type": "string",
      "description": "Optional copyright text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "labelId",
      "type": "string",
      "description": "Optional heading/label ID for the footer content. Can be used with aria-labelledby.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "links",
      "type": "FooterLink[]",
      "description": "Array of footer navigation links.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "logo",
      "type": "LogoSource",
      "description": "Optional logo element (e.g., <img>, <Logo />).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "logoAriaLabel",
      "type": "string",
      "description": "Accessible name for the logo when it is rendered as an image or custom node.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "logoDecorative",
      "type": "boolean",
      "description": "If true, the logo is decorative and should be hidden from assistive tech.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "navAriaLabel",
      "type": "string",
      "description": "Accessible label for the site links navigation region. Defaults can still be provided in the base component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the component. ('none' | 'small' | 'medium' | 'large' | 'full')",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the component. ('none' | 'light' | 'medium' | 'strong' | 'intense')",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "showThemeSelect",
      "type": "boolean",
      "description": "Whether to show the theme selector dropdown.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "socialLinks",
      "type": "SocialLink[]",
      "description": "Array of social links with icons.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "socialNavAriaLabel",
      "type": "string",
      "description": "Accessible label for the social links navigation region. Defaults can still be provided in the base component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling. ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear')",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "themeSelectAriaLabel",
      "type": "string",
      "description": "Accessible label for the theme selector region/container.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
