/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const footerPropDocs: GeneratedComponentDoc = {
  "name": "Footer",
  "interfaceName": "FooterProps",
  "description": "Props for the Footer component.",
  "sourcePath": "src\\components\\Footer\\Footer.types.ts",
  "props": [
    {
      "name": "actionGroupClassName",
      "type": "string",
      "description": "Optional custom class name for action groups, such as the Connect group.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "actionsClassName",
      "type": "string",
      "description": "Optional custom class name for the actions column.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Describes the footer landmark via external element IDs.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the overall footer landmark. Use when multiple contentinfo landmarks may appear on the page.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Accessible label reference for the overall footer landmark.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "attachment",
      "type": "AttachmentType",
      "description": "Attachment type for how the footer is positioned. ('static' | 'fixed' | 'sticky')",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "bottomClassName",
      "type": "string",
      "description": "Optional custom class name for the bottom bar.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "bottomCopyrightClassName",
      "type": "string",
      "description": "Optional custom class name for the bottom copyright text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "bottomEnd",
      "type": "ReactNode",
      "description": "Content shown on the right side of the bottom bar. Example: \"Secure Environment\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "bottomEndClassName",
      "type": "string",
      "description": "Optional custom class name for the bottom-end content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "brandClassName",
      "type": "string",
      "description": "Optional custom class name for the columns layout brand area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "brandDescription",
      "type": "ReactNode",
      "description": "Optional brand description text displayed in the brand column.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "brandDescriptionClassName",
      "type": "string",
      "description": "Optional custom class name for the brand description.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "brandHref",
      "type": "string",
      "description": "Optional href for the brand/logo area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "brandLinkClassName",
      "type": "string",
      "description": "Optional custom class name for the brand link/wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "brandTitle",
      "type": "ReactNode",
      "description": "Optional brand title displayed beside or below the logo.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "brandTitleClassName",
      "type": "string",
      "description": "Optional custom class name for the brand title.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional class name for custom styles.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Optional custom class name for the main footer content wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "copyright",
      "type": "string",
      "description": "Optional copyright text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "copyrightClassName",
      "type": "string",
      "description": "Optional custom class name for copyright when rendered outside the bottom bar.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "copyrightInBottom",
      "type": "boolean",
      "description": "Whether copyright should render in the bottom bar. Useful for column layouts.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "labelId",
      "type": "string",
      "description": "Optional heading/label ID for the footer content. Can be used with aria-labelledby.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "layout",
      "type": "FooterLayout",
      "description": "Footer layout style. \"inline\" keeps the older compact layout. \"columns\" supports brand, grouped sections, social links, and bottom bar.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "leftClassName",
      "type": "string",
      "description": "Optional custom class name for the inline layout left area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "linkClassName",
      "type": "string",
      "description": "Optional custom class name applied to inline footer links.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "links",
      "type": "FooterLink[]",
      "description": "Array of footer navigation links.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "linksClassName",
      "type": "string",
      "description": "Optional custom class name for the inline layout links nav.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "logo",
      "type": "LogoSource",
      "description": "Optional logo element (e.g., <img>, <Logo />).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "logoAriaLabel",
      "type": "string",
      "description": "Accessible name for the logo when it is rendered as an image or custom node.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "logoClassName",
      "type": "string",
      "description": "Optional custom class name for the logo wrapper/image.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "logoDecorative",
      "type": "boolean",
      "description": "If true, the logo is decorative and should be hidden from assistive tech.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "navAriaLabel",
      "type": "string",
      "description": "Accessible label for the site links navigation region. Defaults can still be provided in the base component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the component. ('none' | 'small' | 'medium' | 'large' | 'full')",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "sections",
      "type": "FooterSection[]",
      "description": "Grouped footer link sections. When omitted, the old `links` prop is still supported.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "sectionsClassName",
      "type": "string",
      "description": "Optional custom class name for the grouped sections wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "sectionTitleClassName",
      "type": "string",
      "description": "Optional custom class name for section titles in the columns layout.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the component. ('none' | 'light' | 'medium' | 'strong' | 'intense')",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "showThemeSelect",
      "type": "boolean",
      "description": "Whether to show the theme selector dropdown.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "socialClassName",
      "type": "string",
      "description": "Optional custom class name for the social links nav.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "socialLinks",
      "type": "SocialLink[]",
      "description": "Array of social links with icons.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "socialNavAriaLabel",
      "type": "string",
      "description": "Accessible label for the social links navigation region. Defaults can still be provided in the base component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling. ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear')",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "themeSelectAriaLabel",
      "type": "string",
      "description": "Accessible label for the theme selector region/container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "themeToggleClassName",
      "type": "string",
      "description": "Optional custom class name for the theme selector wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
