/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const iconButtonPropDocs: GeneratedComponentDoc = {
  "name": "IconButton",
  "interfaceName": "IconButtonProps",
  "description": "Props for the IconButton component.",
  "sourcePath": "src\\components\\IconButton\\IconButton.types.ts",
  "props": [
    {
      "name": "aria-atomic",
      "type": "boolean",
      "description": "Indicates whether screen readers should present all of a live region at once.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-busy",
      "type": "boolean",
      "description": "Indicates whether the button is busy, such as while loading.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-checked",
      "type": "boolean | \"mixed\"",
      "description": "Indicates the current checked state when the icon button behaves like a checkable control.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-controls",
      "type": "string",
      "description": "Identifies the element whose contents or presence are controlled by this button.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-current",
      "type": "boolean | \"time\" | \"page\" | \"step\" | \"location\" | \"date\"",
      "description": "Indicates the current active item within a related set, when applicable.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional ID reference to one or more elements that describe this control.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-errormessage",
      "type": "string",
      "description": "Optional ID reference to an error message element for this control.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-expanded",
      "type": "boolean",
      "description": "Indicates whether the associated popup element is currently expanded.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-haspopup",
      "type": "boolean | \"dialog\" | \"grid\" | \"listbox\" | \"menu\" | \"tree\"",
      "description": "Indicates whether activating the control opens a popup element such as a menu or dialog.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "description": "Indicates whether the control is currently invalid.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for screen readers. Required for icon-only usage unless title is provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional ID reference to one or more elements that label this control.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Indicates whether the element should be announced as live region content.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-pressed",
      "type": "boolean | \"mixed\"",
      "description": "Indicates the current pressed state for toggle-style icon buttons.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-selected",
      "type": "boolean",
      "description": "Indicates the current selected state when used in selectable patterns.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Custom class name for additional styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the button should be disabled.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "href",
      "type": "string",
      "description": "Optional href to turn the button into a link.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "icon",
      "type": "ComponentType<{ className?: string; \"aria-hidden\"?: boolean; focusable?: boolean; \"data-testid\"?: string; }>",
      "description": "Icon component to render inside the button. Should be a React component, e.g., from `react-icons`.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconClassName",
      "type": "string",
      "description": "Custom class name for the icon.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional id for the root button or link element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "isExternal",
      "type": "boolean",
      "description": "If true, opens the link in a new tab (used with `href`).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether to show a loading spinner instead of the icon.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onClick",
      "type": "((e: React.MouseEvent<HTMLElement>) => void)",
      "description": "Click event handler for the button.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether the button should use an outline style.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "rel",
      "type": "string",
      "description": "Optional rel attribute for link mode.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "React.AriaRole",
      "description": "Optional role override for advanced accessible interaction patterns.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style of the button. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style of the button. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the button. One of: \"xs\" | \"small\" | \"medium\" | \"large\" | \"xl\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the button. One of: \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "tabIndex",
      "type": "number",
      "description": "Optional tab index override.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "target",
      "type": "React.HTMLAttributeAnchorTarget",
      "description": "Optional target attribute for link mode.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme style of the button. One of: \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "title",
      "type": "string",
      "description": "Title attribute (native browser tooltip text).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "tooltip",
      "type": "string",
      "description": "Tooltip text (not rendered automatically—use `title` for built-in browser tooltip).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "type",
      "type": "\"button\" | \"reset\" | \"submit\"",
      "description": "Native button type. One of: \"button\" | \"reset\" | \"submit\"",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
