/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const markdownRendererPropDocs: GeneratedComponentDoc = {
  "name": "MarkdownRenderer",
  "interfaceName": "MarkdownRendererProps",
  "description": "Props for the MarkdownRenderer component.",
  "sourcePath": "src\\components\\MarkdownRenderer\\MarkdownRenderer.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ID of an element that describes the markdown region.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the markdown region. Use this when there is no visible heading associated with the content.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ID of an element that labels the markdown region. Prefer this when a visible heading already exists.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional additional class name for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "content",
      "type": "string",
      "description": "Raw markdown content to be rendered as HTML.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "language",
      "type": "string",
      "description": "Language of the rendered markdown content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "React.AriaRole",
      "description": "Optional ARIA role for the wrapper element. Defaults to \"region\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Optional rounding style for the rendered container. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Optional shadow styling for the rendered container. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "tabIndex",
      "type": "number",
      "description": "Optional tab index for keyboard focus management.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
