/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const messagePopupPropDocs: GeneratedComponentDoc = {
  "name": "MessagePopup",
  "interfaceName": "MessagePopupProps",
  "description": "Props for the MessagePopup component.",
  "sourcePath": "src\\components\\MessagePopup\\MessagePopup.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional ID of an external element that describes the dialog. Useful when the popup description should point to custom content.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the dialog when no visible title is available. Prefer this when the popup does not render a heading.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label-close-button",
      "type": "string",
      "description": "Accessible label for the close button. Defaults to \"Close popup\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional ID of an external element that labels the dialog. Overrides the internally generated label association when provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Optional aria-live politeness setting for announcing popup content. Only use when the popup message should be announced dynamically.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "cancelText",
      "type": "string",
      "description": "Optional text for the cancel button (default: \"Cancel\").",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional additional class names for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "confirmText",
      "type": "string",
      "description": "Optional text for the confirm button (default: \"Confirm\").",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "controlsRounding",
      "type": "RoundingType",
      "description": "Optional rounding for controls in the message popup. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for targeting the component during testing.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "dialogRole",
      "type": "\"alertdialog\" | \"dialog\"",
      "description": "Optional role for the popup container. Defaults to \"dialog\". Use \"alertdialog\" for urgent confirmations.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "message",
      "type": "string",
      "description": "Message text to be displayed within the popup dialog.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onCancel",
      "type": "(() => void)",
      "description": "Optional callback when the user cancels the action.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onClose",
      "type": "() => void",
      "description": "Callback function to execute when the popup is closed.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onConfirm",
      "type": "(() => void)",
      "description": "Optional callback when the user confirms the message.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Optional rounding for the message popup. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Optional shadow for the message popup. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "description": "Optional title shown in a top bar. If provided, a header section is rendered above the message.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
