/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const modalPropDocs: GeneratedComponentDoc = {
  "name": "Modal",
  "interfaceName": "ModalProps",
  "description": "Props for the Modal component.",
  "sourcePath": "src\\components\\Modal\\Modal.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "The id of an element that describes the modal dialog. Useful for linking help text, instructions, or supporting content.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the modal dialog. Use this when the modal does not have a visible title or when you want to provide a custom accessible name for screen readers.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "The id of an element that labels the modal dialog. Prefer this when a visible heading or custom header should act as the dialog label.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "children",
      "type": "ReactElement<unknown, string | JSXElementConstructor<any>>",
      "description": "The content to be rendered inside the modal. Expected to be a single React element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class names for custom styling the modal content.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "closeButtonAriaLabel",
      "type": "string",
      "description": "Accessible label for the close button. Defaults to \"Close modal\" in the base implementation.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "footer",
      "type": "ReactNode",
      "description": "Optional footer content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "header",
      "type": "ReactNode",
      "description": "Optional custom header content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onClose",
      "type": "() => void",
      "description": "Callback function fired when the modal is closed.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "open",
      "type": "boolean",
      "description": "Controls whether the modal is open. - If omitted, the modal is considered open when rendered. - If provided, the modal opens/closes based on this value.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the modal corners. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the modal. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "description": "Optional modal title used for accessible labelling and default header content.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
