/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const pagerPropDocs: GeneratedComponentDoc = {
  "name": "Pager",
  "interfaceName": "PagerProps",
  "description": "Props for the Pager (pagination) component.",
  "sourcePath": "src\\components\\Pager\\Pager.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional description id for the pagination navigation region.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the pagination navigation region.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional labelledby id for the pagination navigation region.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional extra class name(s) for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "currentPage",
      "type": "number",
      "description": "The currently active page (1-indexed).",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "getLiveRegionMessage",
      "type": "((currentPage: number, totalPages: number) => string)",
      "description": "Function used to generate the live region status message.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "getPageAriaLabel",
      "type": "((page: number, isActive: boolean) => string)",
      "description": "Function used to generate an accessible label for each page button.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "itemsPerPage",
      "type": "number",
      "description": "Number of items to display per page.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "liveRegionAriaLive",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "ARIA live politeness setting for the status message.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "next-button-aria-label",
      "type": "string",
      "description": "Accessible label for the next page button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onPageChange",
      "type": "(page: number) => void",
      "description": "Callback function invoked when a page change occurs.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "page-list-aria-label",
      "type": "string",
      "description": "Accessible label for the page list.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "previous-button-aria-label",
      "type": "string",
      "description": "Accessible label for the previous page button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the controls. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "serverControlled",
      "type": "boolean",
      "description": "Enables server side control of the paging.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the controls. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Optional size modifier for pagination buttons. One of: \"xs\" | \"small\" | \"medium\" | \"large\" | \"xl\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Optional state of the component for feedback styling. One of: \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Optional theme to apply for pagination. One of: \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "totalItems",
      "type": "number",
      "description": "Total number of items to paginate through.",
      "required": true,
      "inherited": false,
      "category": "props"
    }
  ]
};
