/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const popoverPropDocs: GeneratedComponentDoc = {
  "name": "Popover",
  "interfaceName": "PopoverProps",
  "description": "Props for the Popover component.",
  "sourcePath": "src\\components\\PopOver\\PopOver.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Associates the popover content with an external description element ID.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the popover content region.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Associates the popover content with an external label element ID.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-modal",
      "type": "boolean",
      "description": "Whether the popover should be announced as modal when role is dialog.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional additional class name(s) for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "content",
      "type": "ReactNode",
      "description": "Content to be displayed inside the popover.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Disables interaction with the trigger and popover.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional ID for the popover content element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "placement",
      "type": "\"left\" | \"right\" | \"top\" | \"bottom\"",
      "description": "Placement of the popover relative to the trigger element. One of: \"top\" | \"bottom\" | \"left\" | \"right\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the popover content. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the popover content. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the popover, for feedback styling. One of: \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme for the popover styling. One of: \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "trigger",
      "type": "ReactNode",
      "description": "Trigger element that toggles the popover's visibility.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "triggerAriaLabel",
      "type": "string",
      "description": "Accessible label for the trigger button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "triggerTitle",
      "type": "string",
      "description": "Accessible label for the trigger button when expanded/collapsed state needs custom wording.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
