/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const progressBarPropDocs: GeneratedComponentDoc = {
  "name": "ProgressBar",
  "interfaceName": "ProgressBarProps",
  "description": "Props for the ProgressBar component.",
  "sourcePath": "src\\components\\ProgressBar\\ProgressBar.types.ts",
  "props": [
    {
      "name": "animated",
      "type": "boolean",
      "description": "If true, applies an animated effect to the progress bar.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ID of the element that describes the progress bar. Useful for extra context or status messaging.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the progress bar. Use this when no visible label exists.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ID of the element that labels the progress bar. Prefer this when there is a visible label in the UI.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-valuetext",
      "type": "string",
      "description": "Custom accessible text for screen readers. Example: \"Uploading 3 of 5 files\"",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional additional class name(s) for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing purposes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "description",
      "type": "ReactNode",
      "description": "Optional description content rendered for assistive technology.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "descriptionId",
      "type": "string",
      "description": "Optional id applied to the description container. Useful when connecting the description with aria-describedby.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "indeterminate",
      "type": "boolean",
      "description": "If true, the progress bar shows an indeterminate animation. When true, the value prop is ignored.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Optional label describing what the progress represents. Example: \"Uploading files\", \"Build progress\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelId",
      "type": "string",
      "description": "Optional id applied to the visible label container. Useful when connecting the label with aria-labelledby.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the progress bar.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding to apply to the progress bar. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow to apply to the progress bar. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the progress bar. One of: \"xs\" | \"small\" | \"medium\" | \"large\" | \"xl\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the progress bar. One of: \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme for styling the progress bar. One of: \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "value",
      "type": "number",
      "description": "Value of progress (0 to 100). Ignored if `indeterminate` is true.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
