/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const radioButtonPropDocs: GeneratedComponentDoc = {
  "name": "RadioButton",
  "interfaceName": "RadioButtonProps",
  "description": "Props for the RadioButton component.",
  "sourcePath": "src\\components\\RadioButton\\RadioButton.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Identifies the element (or elements) that describe this radio button.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-invalid",
      "type": "boolean | \"true\" | \"false\"",
      "description": "Marks the radio button as invalid for accessibility.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Provides an accessible label when no visible label is present.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Identifies the element (or elements) that label this radio button. Usually not needed when using the built-in `label` prop, but available for advanced cases.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-required",
      "type": "boolean | \"true\" | \"false\"",
      "description": "Indicates whether this radio button is required as part of a group.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "checked",
      "type": "boolean",
      "description": "Whether this radio button is currently checked.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the radio button is disabled.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "string",
      "description": "The label text displayed next to the radio button.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "description": "Callback triggered when the radio button's value changes.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the radio button. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style of the radio button. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the radio button. One of: \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme applied for styling. One of: \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "value",
      "type": "string",
      "description": "The value associated with this radio button.",
      "required": true,
      "inherited": false,
      "category": "props"
    }
  ]
};
