/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const selectPropDocs: GeneratedComponentDoc = {
  "name": "Select",
  "interfaceName": "SelectProps",
  "description": "Props for the Select component.",
  "sourcePath": "src\\components\\Select\\Select.types.ts",
  "props": [
    {
      "name": "aria-busy",
      "type": "boolean",
      "description": "Indicates the select is busy, useful while async options are loading.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional aria-describedby id reference for helper/error text.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-description",
      "type": "string",
      "description": "Optional description text for the select element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "description": "Marks the field as invalid for assistive technology. If omitted, component logic may still infer invalid from state === \"error\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Optional aria-label for screen readers. Useful when no visible label is provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional aria-labelledby id reference. Prefer this when an external label element exists.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Optional aria-live setting for async status messaging.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "description": "Indicates the field is required to assistive technology.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "asyncOptions",
      "type": "((query: string) => Promise<Option[]>)",
      "description": "If provided, the select element will render options asynchronously. Should return a Promise resolving to Option[] based on search query.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "autoComplete",
      "type": "string",
      "description": "Optional autocomplete behavior for compatible use cases.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name(s) for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the select element is disabled.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "form",
      "type": "string",
      "description": "Optional form association.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional id for the underlying select element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Optional visible label describing what the select is for.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the select.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "name",
      "type": "string",
      "description": "Name for the select element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "description": "Callback fired when the selected option changes. Receives the new value as an argument.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "options",
      "type": "Option[]",
      "description": "An array of options that will be rendered as dropdown choices.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "If true, the select element is styled as outlined.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "placeholder",
      "type": "string",
      "description": "Placeholder text to display when no option is selected.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "pollInterval",
      "type": "number",
      "description": "Optional polling interval for updating options in milliseconds.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether the select element is required.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "AriaRole",
      "description": "Optional role override. Usually not needed for a native select, but included for flexibility.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style of the select element. \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style of the select element. \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State variant for styling. \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "tabIndex",
      "type": "number",
      "description": "Optional tab index for keyboard navigation control.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme for styling. \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "value",
      "type": "string",
      "description": "The current selected value.",
      "required": true,
      "inherited": false,
      "category": "props"
    }
  ]
};
