/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const skeletonPropDocs: GeneratedComponentDoc = {
  "name": "Skeleton",
  "interfaceName": "SkeletonProps",
  "description": "Props for the SkeletonLoader component.",
  "sourcePath": "src\\components\\Skeleton\\Skeleton.types.ts",
  "props": [
    {
      "name": "aria-busy",
      "type": "boolean",
      "description": "Overrides the default busy state.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional ID reference to additional descriptive content.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-hidden",
      "type": "boolean",
      "description": "Allows explicit control over whether the skeleton should be exposed to assistive technology.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Optional ARIA label for the skeleton. Preferred when you want to directly label the status region.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional ID reference to an external label element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Overrides the default ARIA live politeness when announce is enabled.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name(s) for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "height",
      "type": "string | number",
      "description": "Height of the skeleton loader (e.g., \"100%\", \"50px\", or a number representing pixels).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Accessibility label for screen readers. Used as fallback hidden descriptive text when announce is enabled.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "React.AriaRole",
      "description": "Optional semantic role override. Defaults to \"status\" when announce is enabled.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the skeleton. \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the skeleton loader. \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "width",
      "type": "string | number",
      "description": "Width of the skeleton loader (e.g., \"100%\", \"200px\", or a number representing pixels).",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
