/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const tabsPropDocs: GeneratedComponentDoc = {
  "name": "Tabs",
  "interfaceName": "TabsProps",
  "description": "Props for the Tabs component.",
  "sourcePath": "src\\components\\Tabs\\Tabs.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Accessible description id for the tablist.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible name for the tablist.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Accessible labelledby id for the tablist. Preferred over aria-label when provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Optional aria-live setting if tab changes should be announced by a related region.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Custom class names to apply to the tabs container.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test ID for testing purposes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "defaultIndex",
      "type": "number",
      "description": "Uncontrolled initial index.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "idBase",
      "type": "string",
      "description": "Optional stable base used to create ids: `${idBase}-tab-${i}` and `${idBase}-panel-${i}`",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "((index: number) => void)",
      "description": "Callback when the active tab changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the tabs. \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style of the tabs. \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the tabs. \"xs\" | \"small\" | \"medium\" | \"large\" | \"xl\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the tabs. \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "tabListId",
      "type": "string",
      "description": "Optional id for the tablist element itself.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "tabs",
      "type": "Tab[]",
      "description": "Array of tabs to display.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme for styling the tabs. \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "value",
      "type": "number",
      "description": "Controlled active tab index.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
