/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const tagInputPropDocs: GeneratedComponentDoc = {
  "name": "TagInput",
  "interfaceName": "TagInputProps",
  "description": "Props for the TagInput component.",
  "sourcePath": "src\\components\\TagInput\\TagInput.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "References the ID of an external element that describes the tag input group. Merged with the internal accessibility description/status when provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-description",
      "type": "string",
      "description": "Optional screen reader description for the input behavior. This is announced through an internally rendered description element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the overall tag input group. Used when no external aria-labelledby is provided. Defaults to \"Tag Input\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "References the ID of an external element that labels the tag input group. Takes precedence over \"aria-label\" when provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "debounceMs",
      "type": "number",
      "description": "Debounce time (ms) for suggestions/autocomplete fetches.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fetchSuggestions",
      "type": "((query: string) => Promise<string[]>)",
      "description": "Optional function to fetch autocomplete suggestions based on input query. Should return a promise resolving to a string array.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "idBase",
      "type": "string",
      "description": "Custom ID base for stable accessibility relationships. Can be used to generate predictable ids for label, description, listbox, input, and status elements.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputAriaDescribedBy",
      "type": "string",
      "description": "References the ID of an external element that describes the text input. Merged with the internal description/status when provided.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputAriaLabel",
      "type": "string",
      "description": "Optional accessible label for the text input itself. Defaults to \"Add new tag\".",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputAriaLabelledBy",
      "type": "string",
      "description": "References the ID of an external element that labels the text input. Takes precedence over inputAriaLabel when provided.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "((tags: string[]) => void)",
      "description": "Callback fired when tags change. Receives the new array of tags.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "placeholder",
      "type": "string",
      "description": "Placeholder text displayed in the input when empty.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "removeTagButtonLabel",
      "type": "string",
      "description": "Accessible label prefix for remove-tag buttons. Example output: \"Remove tag React\". Defaults to \"Remove tag\".",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the input and tags. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the input and tags. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the input and tags. One of: \"xs\" | \"small\" | \"medium\" | \"large\" | \"xl\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the input (for feedback/validation). One of: \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "suggestionsAriaLabel",
      "type": "string",
      "description": "Accessible label for the suggestions listbox. Defaults to \"Tag suggestions\".",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "tags",
      "type": "string[]",
      "description": "Array of current tags.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme for styling the input and tags. One of: \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    }
  ]
};
