/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const textInputPropDocs: GeneratedComponentDoc = {
  "name": "TextInput",
  "interfaceName": "TextInputProps",
  "description": "Props for the TextInput component.",
  "sourcePath": "src\\components\\TextInput\\TextInput.types.ts",
  "props": [
    {
      "name": "aria-activedescendant",
      "type": "string",
      "description": "Identifies the current autocomplete suggestion in custom combobox patterns.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-controls",
      "type": "string",
      "description": "Identifies the element controlled by this input.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "References one or more elements that describe the input.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-description",
      "type": "string",
      "description": "Provides a short hint to assistive technologies.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-disabled",
      "type": "boolean",
      "description": "Indicates whether the element is disabled to assistive technologies.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-expanded",
      "type": "boolean",
      "description": "Indicates whether the input controls an expandable popup.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-haspopup",
      "type": "boolean | \"dialog\" | \"grid\" | \"listbox\" | \"menu\" | \"tree\" | \"true\" | \"false\"",
      "description": "Indicates whether a popup such as a listbox, grid, or dialog is available.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-invalid",
      "type": "boolean | \"true\" | \"false\" | \"grammar\" | \"spelling\"",
      "description": "Indicates whether the input has an invalid value.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Explicit accessible label for the outer field region if needed.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "References one or more elements that label the input.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-readonly",
      "type": "boolean",
      "description": "Indicates whether the input is read-only to assistive technologies.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "description": "Indicates whether user input is required.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "autocomplete",
      "type": "boolean",
      "description": "Controls whether autocomplete is enabled. Pass true for \"on\" or false for \"off\".",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "icon",
      "type": "ComponentType<{ className?: string; \"aria-hidden\"?: boolean; }>",
      "description": "Optional icon component displayed beside the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Optional visible label/title for the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label. \"top\" | \"left\" | \"right\" | \"bottom\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "maxLength",
      "type": "number",
      "description": "Maximum length of the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "((value: string, event: React.ChangeEvent<HTMLInputElement>) => void)",
      "description": "Called when the input value changes. Returns both the current value and the original change event.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "If true, the input is outlined instead of filled.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "password",
      "type": "boolean",
      "description": "If true, the input behaves as a password field and shows a visibility toggle.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "description": "If true, the input is rendered in read-only mode.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "React.AriaRole",
      "description": "Declares the role when this input is used in advanced patterns such as searchbox, combobox, or spinbutton.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the component. \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the component. \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only. Useful for dynamic status or extra context.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the input. \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling. \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    }
  ]
};
