/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const tooltipPropDocs: GeneratedComponentDoc = {
  "name": "Tooltip",
  "interfaceName": "TooltipProps",
  "description": "Props for the Tooltip component.",
  "sourcePath": "src\\components\\Tooltip\\Tooltip.types.ts",
  "props": [
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label applied to the tooltip itself. Use when the tooltip needs an explicit accessible name.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Accessible labelling reference for the tooltip itself.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "The element that triggers the tooltip.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "content",
      "type": "string",
      "description": "The content text displayed inside the tooltip.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional custom id for the tooltip element. If omitted, a stable generated id is used.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "keepMountedWhenHidden",
      "type": "boolean",
      "description": "Whether the tooltip should remain in the accessibility tree when hidden. Defaults to false behavior via aria-hidden.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "position",
      "type": "\"left\" | \"right\" | \"top\" | \"bottom\"",
      "description": "The position of the tooltip relative to the target element. \"top\" | \"bottom\" | \"left\" | \"right\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style of the tooltip. \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style of the tooltip. \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the tooltip for visual feedback. \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme style of the tooltip. \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "triggerAriaDescribedBy",
      "type": "string",
      "description": "Additional describedby ids to keep on the trigger element alongside the tooltip id when visible.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "triggerAriaLabel",
      "type": "string",
      "description": "Accessible label applied to the trigger element. Helpful when the trigger has no visible text or icon-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "triggerAriaLabelledBy",
      "type": "string",
      "description": "Accessible labelledby reference applied to the trigger element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "triggerId",
      "type": "string",
      "description": "Optional id for the trigger element.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
