/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

export interface GeneratedPropDoc {
  name: string;
  type: string;
  description: string;
  required: boolean;
  inherited: boolean;
  category: string;
}

export interface GeneratedComponentDoc {
  name: string;
  interfaceName: string;
  description: string;
  sourcePath: string;
  props: GeneratedPropDoc[];
}
