/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const typographyPropDocs: GeneratedComponentDoc = {
  "name": "Typography",
  "interfaceName": "TypographyProps",
  "description": "",
  "sourcePath": "src\\components\\Typography\\Typography.types.ts",
  "props": [
    {
      "name": "align",
      "type": "TypographyAlign",
      "description": "Horizontal text alignment.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-atomic",
      "type": "boolean",
      "description": "Whether assistive technologies should present the entire updated region when part of a live region changes.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-busy",
      "type": "boolean",
      "description": "Indicates whether the element is currently being updated, such as during loading.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "References the id of another element that describes this element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-hidden",
      "type": "boolean",
      "description": "Whether the element should be hidden from assistive technologies.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Defines an accessible label for the element when a visible label is not sufficient.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "References the id of another element that labels this element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Indicates that the element will be updated and describes how updates should be announced.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "as",
      "type": "ElementType",
      "description": "The HTML element or custom component to render as. For example: `\"p\"`, `\"span\"`, `\"h1\"`, or a custom React component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "The content to render inside the typography component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional custom CSS class name for the root element.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional unique id for the root element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "italic",
      "type": "boolean",
      "description": "Whether the text should be displayed in italic style.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "noWrap",
      "type": "boolean",
      "description": "Whether the text should remain on a single line without wrapping.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "AriaRole",
      "description": "Optional ARIA role for the rendered element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "srOnly",
      "type": "boolean",
      "description": "Whether the text should be visually hidden but still available to screen readers.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "style",
      "type": "CSSProperties",
      "description": "Optional inline styles applied to the root element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test id used for testing the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "TypographyTheme",
      "description": "Visual theme style applied to the typography.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "title",
      "type": "string",
      "description": "Advisory text for the element, typically shown as a tooltip on hover.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "truncate",
      "type": "boolean",
      "description": "Whether overflowing text should be truncated, typically with an ellipsis.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "underline",
      "type": "boolean",
      "description": "Whether the text should be underlined.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "TypographyVariant",
      "description": "Predefined typography style variant. Examples may include headings, body text, captions, or labels.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "weight",
      "type": "TypographyWeight",
      "description": "Font weight of the text.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
